### PR TITLE
updates to support php between 5.5 and 7.x

### PR DESCRIPTION
**Pull request by davidpesce**
Adding required changes within submodules to support php 5.5-7.x.

@ryansmith94 what's the process for submitting the composer.lock file?

### CODE REVIEW

**Comment by ryansmith94** [comment]
Hey @davidpesce, just add and commit it like any other file 😄 Travis will make sure it works

**Comment by ryansmith94** [comment]
You need to run `php composer.phar update` I think to get composer to update it.

**Comment by davidpesce** [comment]
OK, should be set. I also found a formatting error in my composer.json and fixed it.

**Comment by ryansmith94** [comment]
Nice one!

**Pull request merged**
