### PR TITLE
Added createEvents() methods

### PR DESCRIPTION
**Pull request by micaherne**
Hi, here is a patch to add support for multiple events, to help solve jlowe64/moodle-logstore_xapi#43.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Before I merge this, please can you remove:

1. The createEvent method in src/Controller.php
1. The createEvent method in src/Repository.php
1. The create_event method in tests/TestRepository.php

**Comment by jlowe64** [comment]
@micaherne If you have the time, could you look at the things @ryansmith94 posted here for pre-merge? I think if you could do this, then I could start the testing process again and see if we can make a release for today or tomorrow!

Thank you! :)

**Comment by micaherne** [comment]
@jlowe64 Thanks for pointing that out - I'd missed @ryansmith94's message. I've updated the patch with these changes now. Unit tests are still passing.

**Comment by ryansmith94** [comment]
Thanks @micaherne :+1:

**Comment by jlowe64** [comment]
Thanks @micaherne!

**Pull request merged**
