### PR TITLE
Push context source back to translator

### PR DESCRIPTION
**Pull request by garemoko**
@ryansmith94 this is *much* neater. Thanks for picking this up. I'm starting to understand the structure now.

### CODE REVIEW

**Comment by garemoko** [comment]
Just realized I used the wrong branch for this. Nevermind.

**Comment by ryansmith94** [comment]
Nice that does look much neater, I thought there was something odd about this before but I couldn't quite grasp what it was. No worries. Awesome! :+1: Let me know when this is ready for review :smile:

**Comment by garemoko** [comment]
@ryansmith94 it's ready. Working on a translator PR now too.

**Comment by ryansmith94** [comment]
Awesome, loving this fast work @garemoko :+1:

**Pull request merged**
