### PR TITLE
Add Question answered

### PR DESCRIPTION
**Pull request by garemoko**
This is sort of working right now. The problems are:

* ~~Only the second statement in my test quiz is arriving in Watershed. I need to do some debugging around this to try and figure out why.~~
* ~~I need to do docs and tests.~~ 
* ~~I need to test against Watershed's quiz reporting to make sure I didn't miss anything important.~~ 
* ~~i need to test "unsupported" question types and make sure we fail gracefully.~~ https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/30

### CODE REVIEW

**Comment by garemoko** [comment]
The reason this is failing is that I'm not processing choices:
```
"choices": {
				"8": "dsf;s",
				"9": "sdfds",
				"10": "nooooo"
			}
```
Instead of
```
 "choices": [
        {
            "id": "golf", 
            "description": {
                "en-US": "Golf Example"
            }
        },
        {
            "id": "facebook", 
            "description": {
                "en-US": "Facebook App"
            }
        },
        {
            "id": "tetris", 
            "description": {
                "en-US": "Tetris Example"
            }
        },
        {
            "id": "scrabble", 
            "description": {
                "en-US": "Scrabble Example"
            }
        }
    ]
```

**Comment by garemoko** [comment]
This is now sending all statements. Just needs docs, tests and some manual testing against Watershed. Likely be Wednesday when i need look at this, but I may get some time sooner.

**Comment by ryansmith94** [comment]
Ok good stuff @garemoko :+1:

**Comment by garemoko** [comment]
Bug: numeric type questions do not feed through the response if the response is not one of the options.

**Comment by garemoko** [comment]
@ryansmith94 ready for review

**Comment by ryansmith94** [comment]
Awesome thanks @garemoko :+1:

**Pull request merged**
